### ISSUE TITLE
--concurrency without value should fail

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#1367]
See https://github.com/avajs/ava/issues/1365#issuecomment-296146387. `--concurrency` requires a value but you can run AVA without specifying it.

**Comment by yatharthk** [comment]
@novemberborn We need to add a warning over here and that's it or something more is expected? Are new tests required?

**Comment by yatharthk** [comment]
@novemberborn I wrote this code:

```javascript
if (hasFlag('--concurrency') || hasFlag('-c')) {
        throw new Error(colors.error(figures.cross) + ' The --concurrency and -c flags must be provided the maximum number of test files to run with.');
}
```

with this test:

```javascript
test('bails when config does not contain `--concurrency` and `-c` values', t => {
	execCli(['test.js'], {dirname: 'fixture/concurrency'}, (err, stdout, stderr) => {
		t.is(err.code, 1);
		t.match(stderr, 'The --concurrency and -c flags must be provided the maximum number of test files to run with.');
		t.end();
	});
});
```

which fails with this error:

```
bails when config does not contain `--concurrency` and `-c` values
  not ok spawn /Users/yatharthk/.node-spawn-wrap-62339-36f9a5f0c8ca/node ENOENT
    at:
      line: 1026
      column: 11
      file: util.js
      function: exports._errnoException
    code: ENOENT
    errno: ENOENT
    syscall: spawn /Users/yatharthk/.node-spawn-wrap-62339-36f9a5f0c8ca/node
    path: /Users/yatharthk/.node-spawn-wrap-62339-36f9a5f0c8ca/node
    spawnargs:
      - ../../../cli.js
      - test.js
    test: bails when config does not contain `--concurrency` and `-c` values
```

Can you help me understand what's going on? Probably because I also want to understand what does `{dirname: 'fixture/concurrency'}` config does exactly!
