### ISSUE TITLE
Parallel CI runs in GitLab CI break matrix

### ISSUE THREAD

**Issue by lenovouser** [avajs/ava#2994]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2425%20Funded-%2300A156.svg" />](https://issuehunt.io/r/avajs/ava/issues/2994)

When using a GitLab CI configuration like this:

```yaml
test:
    image: node:$NODE_VERSION
    stage: test
    interruptible: true
    script:
        - npm run test
    parallel:
        matrix:
            - NODE_VERSION: [14, 16, lts, latest]
```

Ava assumes that the tests are being run in parallel, and thus splits the tests up into four. It then runs only a part of the tests in each node version, instead of testing everything on all node versions. This is the correct behavior when it is set like this:

```yaml
test:
    parallel: 4
```

But not when using the `matrix` keyword, since that is used

> to run a job multiple times in parallel in a single pipeline, but with different variable values for each instance of the job

(From [**`docs.gitlab.com/ci/yaml`**](https://docs.gitlab.com/ee/ci/yaml/#parallelmatrix))

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $25.00)

- [<img src='https://avatars.githubusercontent.com/u/19628635?v=4' alt='panascais' width=24 height=24> panascais](https://issuehunt.io/u/panascais) ($25.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/avajs/ava/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>
